### ISSUE TITLE
Increase default value for `EP_MAX_METHOD_STR_LEN`

### ISSUE THREAD

**Issue by VladyslavTupikin** [InangoSystems/feed-mmx#45]
`EP_MAX_METHOD_STR_LEN` parameter contains value for maximum method string length for MMX Entrypoint. Current default value is `256` but it is not enough for prplMesh because Data Model contains some methods larger than `256` characters. Need to increase it twice, `512` characters enough for prplMesh.

**Comment by VladyslavTupikin** [comment]
Decided to use mmx profile in prplwrt for increasing this variable.
For example it can look like:

```
feeds:
  - name: mmx
    uri: https://github.com/InangoSystems/feed-mmx.git
    tracking_branch: master
    revision: f074f71597f70666fe9dbb45e321948f538b171c

packages:
  - luasocket
  - luaxml
  - mmx-web-lib-chartist
  - libing-gen-utils
  - libmicroxml
  - libmmx-backapi
  - libmmx-frontapi
  - mmx-cli
  - mmx-ep
  - mmx-web
  - inango-prplmesh-en
  - prplmesh-be

diffconfig: |
  CONFIG_EP_MAX_METHOD_STR_LEN=512

```
